import os

SUPABASE_URL = os.getenv(
    "SUPABASE_URL"
)

SUPABASE_ANON_KEY = os.getenv(
    "SUPABASE_ANON_KEY"
)

SUPABASE_SERVICE_ROLE_KEY = os.getenv(
    "SUPABASE_SERVICE_ROLE_KEY"
)

OPENROUTER_API_KEY = os.getenv(
    "OPENROUTER_API_KEY"
)

PINECONE_API_KEY = os.getenv(
    "PINECONE_API_KEY"
)

PINECONE_INDEX_NAME = os.getenv(
    "PINECONE_INDEX_NAME"
)

SECRET_KEY = os.getenv(
    "SECRET_KEY"
)